spring.application.name=Conexion

spring.datasource.url=jdbc:sqlserver://localhost;instanceName=MSSQLLocalDB;databaseName=TALLER;encrypt=true;trustServerCertificate=true

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

